#+title: Proteomics.nix

#+begin_html
<p align="center">
  <a href="https://github.com/pjones/proteomics.nix/actions/workflows/test.yml">
    <img alt="CI" src="https://img.shields.io/github/actions/workflow/status/pjones/proteomics.nix/test.yml?&style=for-the-badge">
  </a>

  <a href="https://github.com/pjones/proteomics.nix/actions/workflows/nightly.yml">
    <img alt="OpenMS Nightly" src="https://img.shields.io/github/actions/workflow/status/pjones/proteomics.nix/nightly.yml?style=for-the-badge&label=OpenMS%20Nightly">
  </a>

  <a href="https://github.com/pjones/proteomics.nix/blob/trunk/LICENSE">
    <img alt="License" src="https://img.shields.io/github/license/pjones/proteomics.nix?style=for-the-badge&color=blue">
  </a>

  <a href="https://github.com/pjones/proteomics.nix/releases">
    <img alt="Release" src="https://img.shields.io/github/v/release/pjones/proteomics.nix?style=for-the-badge">
  </a>
</p>
#+end_html

A [[https://nixos.org/][Nix Flake]] (and Podman container) for easy access to proteomics data
analysis tools such as [[https://openms.de/][OpenMS]].

* Using the Podman/Docker Container

  NOTE: If you are using Docker instead of Podman simply replace the
  word =podman= with =docker= in the following instructions.

  1. Pull the container from GitHub:

     #+begin_src sh
       podman pull ghcr.io/pjones/proteomics.nix:latest
     #+end_src

  2. Run one of the tools in the container:

     For example, execute the =ProteomicsLFQ= tool from the OpenMS
     project and request option help (via the =-h= option).

     #+begin_src sh
       podman run --rm -it -v "$(pwd):/mnt" -w /mnt proteomics.nix ProteomicsLFQ -h
     #+end_src

* Installing Packages via Nix

  1. [[https://nixos.org/download/#download-nix][Install Nix]]

  2. Enable the binary cache (optional)

     This will reduce the number of packages you have to build from
     source.  Ideally you'll be able to get everything from the cache.

     #+begin_src sh
       nix \
         --extra-experimental-features nix-command \
         --extra-experimental-features flakes \
         run nixpkgs#cachix use proteomics
     #+end_src

  3. Install the desired package:

     Note: Replace =PACKAGE= with the name of the desired package.  See
     below for a list of available packages.

     #+begin_src sh
       nix \
         --extra-experimental-features nix-command \
         --extra-experimental-features flakes \
         profile install github:pjones/proteomics.nix#PACKAGE
     #+end_src

* Packages

  - [[https://openms.de/][OpenMS]] (=openms=)

  - [[https://github.com/vdemichev/DiaNN][DIA-NN]] (=diann-academia=)

  - [[https://diatracer.nesvilab.org/][diaTracer]] (=diatracer=)

  - [[https://github.com/smith-chem-wisc/FlashLFQ][FlashLFQ]] (=flashlfq=)

  - [[https://maxquant.org/][MaxQuant]] (=maxquant=) [fn:1] (installed as =MaxQuantCmd=)

  - [[https://github.com/smith-chem-wisc/MetaMorpheus][MetaMorpheus]] (=metamorpheus=)

  - [[https://msfragger.nesvilab.org/][MSFragger]] (=msfragger=)

  - [[http://percolator.ms/][Percolator]] (=percolator=)

  - [[https://uwpr.github.io/Comet/][Comet]] (=comet=)

  - [[https://github.com/MSGFPlus/msgfplus][MS-GF+]] (=msgfplus=)

  - [[https://github.com/thermofisherlsms/RawFileReader][RawFileReader]] (=rawfilereader=)

  - [[https://github.com/compomics/ThermoRawFileParser][ThermoRawFileParser]] (=thermorawfp=)

* Footnotes

[fn:1] This is a non-free proprietary software package.  To use it you
must manually download the software from the vendor.  Attempting to
install the Nix package will provide the necessary instructions.
