{
  # Package helpers:
  lib,
  stdenv,
  wrapQtAppsHook,
  writableTmpDirAsHomeHook,

  # Source and version from the flake:
  src,
  version,

  # Dependencies:
  arrow-cpp,
  boost,
  bzip2,
  cmake,
  coinmp,
  curl,
  darwin,
  dockerTools,
  doxygen,
  eigen,
  glpk,
  graphviz,
  kissfft,
  libsvm,
  libzip,
  openmp,
  opentims,
  python3,
  python3Packages,
  qtbase,
  qtsvg,
  ruby,
  xercesc,
  xz,
  yaml-cpp,
  zlib,
  zstd,

  # Flags:
  enablePython ? true,
}:

let
  # Build-time Python dependencies:
  pythonAndPackages = python3.withPackages (
    py-pkgs: with py-pkgs; [
      build
      cython
      nanobind
      numpy
      pandas
      pip
      py-build-cmake
      pytest
      setuptools
      wheel
    ]
  );

  # Run-time Python dependencies:
  runtimePyDeps =
    pypkgs: with pypkgs; [
      matplotlib
      numpy
      pandas
    ];

  # Compute the name of the Python wheel file that is generated by the
  # build system.
  wheelName =
    let
      cpu = stdenv.hostPlatform.parsed.cpu.name;
      os = if stdenv.hostPlatform.isDarwin then "macosx_0_0" else stdenv.hostPlatform.parsed.kernel.name;
      pyver = lib.concatStrings (lib.take 2 (lib.splitString "." python3.version));
    in
    # Like: pyopenms-3.6.0-cp313-cp313-linux_x86_64.whl
    "pyopenms-${version}-cp${pyver}-cp${pyver}-${os}_${cpu}.whl";

  # The actual derivation:
  package = stdenv.mkDerivation {
    inherit src version;
    pname = "OpenMS";

    doCheck = true;
    checkTarget = "test";
    enableParallelBuilding = true;

    nativeBuildInputs = [
      cmake
      doxygen
      wrapQtAppsHook
    ]
    ++ lib.optionals stdenv.isDarwin [
      darwin.sigtool
      ruby
    ];

    nativeCheckInputs = [
      # File_test checks for a home directory :(
      writableTmpDirAsHomeHook
    ];

    cmakeFlags = [
      # Builds don't have access to the network:
      (lib.cmakeBool "ENABLE_UPDATE_CHECK" false)

      # Boost in nixpkgs doesn't have static libs:
      (lib.cmakeBool "BOOST_USE_STATIC" false)

      # Git objects not available at build time:
      (lib.cmakeBool "GIT_TRACKING" false)

      # Build with Parquet support:
      (lib.cmakeBool "WITH_PARQUET" true)

      # Do we want Python?
      (lib.cmakeBool "PYOPENMS" enablePython)

      # Python dependencies are already available in the build
      # environment we don't need uv:
      (lib.cmakeBool "WITH_UV" false)
    ];

    # Needed to export TOPP XML from the built executable files:
    QT_PLUGIN_PATH = "${qtbase}/lib/qt-6/plugins";
    QT_QPA_PLATFORM = "offscreen";

    buildInputs = [
      arrow-cpp
      boost
      bzip2
      coinmp
      curl
      eigen
      glpk
      graphviz
      kissfft
      libsvm
      libzip
      openmp
      opentims
      qtbase
      qtsvg
      xercesc
      xz
      yaml-cpp
      zlib
      zstd
    ]
    ++ lib.optional enablePython pythonAndPackages;

    patches = [
      ../../patches/openms-nuxl-tests.path
      ../../patches/openms-tims-zstd.patch
      ../../patches/pyopenms-codesign-qt.patch
    ];

    postPatch = ''
      # Get rid of unnecessary uses of `which`:
      find . -type f -name '*.rb' -exec \
        sed -i -E \
          -e 's/`which codesign/`echo echo/g' \
          -e 's/`which /`echo /g' '{}' ';'

      # Let Nix fix the RPATHs:
      (
        echo '#!${ruby}/bin/ruby'
        echo 'puts("Skip RPATH fixup")'
      ) >cmake/MacOSX/fix_dependencies.rb
    '';

    postBuild = lib.optionalString enablePython ''
      make pyopenms_wheel
    '';

    postInstall = lib.optionalString enablePython ''
      mkdir -p "$out/share/whl"
      find pyopenms_wheels -type f -name '*.whl' \
        -exec cp -a '{}' "$out/share/whl/${wheelName}" ';'
    '';

    passthru = {
      # A docker container that only includes OpenMS:
      dockerimg = import ./dockerimg.nix {
        inherit dockerTools;
        openms = package;
      };

      # Just the Python package:
      pyopenms = python3Packages.buildPythonPackage {
        pname = "pyopenms";
        version = version;
        format = "wheel";
        src = "${package}/share/whl/${wheelName}";
        dependencies = runtimePyDeps python3Packages;
        pythonImportsCheck = [ "pyopenms" ];
      };
    };

    meta = {
      description = "Open-source software for LC-MS data management and analyses";
      longDescription = ''
        OpenMS is an open-source software C++ library for LC-MS data
        management and analyses. It offers an infrastructure for rapid
        development of mass spectrometry related software. OpenMS is
        free software available under the three clause BSD license and
        runs under Windows, macOS, and Linux.
      '';
      homepage = "https://openms.de/";
      license = lib.licenses.bsd3;
      maintainers = with lib.maintainers; [ pjones ];
      platforms = lib.platforms.all;
    };
  };
in
package
