{
  lib,
  stdenv,
  fetchFromGitHub,
  cmake,
  wrapQtAppsHook,
  writableTmpDirAsHomeHook,

  boost186,
  bzip2,
  coinmp,
  darwin,
  dockerTools,
  doxygen,
  eigen,
  glpk,
  kissfft,
  libsvm,
  openmp,
  python3,
  python3Packages,
  qtbase,
  qtsvg,
  ruby,
  xercesc,
  xz,
  yaml-cpp,
  zlib,
  zstd,

  enablePython ? true,
}:

let
  version = "3.5.0"; # Must match version number in OpenMS source.
  hash = "sha256-sLYT0cyqr7YhuA9LDIW8v4jdNCnSfLNLqZ6ANNwLERM=";

  # NOTE: This is the actual release commit, but we have to use this
  # instead of the tag because the wrong commit was tagged :(
  preRelease = "c1370fb7f7c478574c9f48797e526ebca7736bee";

  pythonAndPackages = python3.withPackages (
    py-pkgs: with py-pkgs; [
      autowrap
      cython
      numpy
      pandas
      pip
      pytest
      setuptools
      wheel
    ]
  );

  # Run-time Python dependencies:
  runtimePyDeps =
    pypkgs: with pypkgs; [
      matplotlib
      numpy
      pandas
    ];

  # Compute the name of the Python wheel file that is generated by the
  # build system.
  wheelName =
    let
      cpu = stdenv.hostPlatform.parsed.cpu.name;
      os = if stdenv.hostPlatform.isDarwin then "macosx_0_0" else stdenv.hostPlatform.parsed.kernel.name;
      pyver = lib.concatStrings (lib.take 2 (lib.splitString "." python3.version));
    in
    "pyopenms-${version}-cp${pyver}-cp${pyver}-${os}_${cpu}.whl";

  # The actual derivation:
  package = stdenv.mkDerivation {
    inherit version;
    pname = "OpenMS";

    src = fetchFromGitHub {
      inherit hash;
      owner = "OpenMS";
      repo = "OpenMS";
      rev = if preRelease != null then preRelease else "refs/tags/release/${version}";
    };

    doCheck = false;
    checkTarget = "test";
    enableParallelBuilding = true;

    nativeBuildInputs = [
      cmake
      doxygen
      wrapQtAppsHook
    ]
    ++ lib.optionals stdenv.isDarwin [
      darwin.sigtool
      ruby
    ];

    nativeCheckInputs = [
      # File_test checks for a home directory :(
      writableTmpDirAsHomeHook
    ];

    cmakeFlags = [
      # Builds don't have access to the network:
      "-DENABLE_UPDATE_CHECK=OFF"

      # Boost in nixpkgs doesn't have static libs:
      "-DBOOST_USE_STATIC=OFF"

      # Can't run GUI tools during the build:
      "-DHAS_XSERVER=OFF"

      # Git objects not available at build time:
      "-DGIT_TRACKING=OFF"

    ]
    ++ lib.optional enablePython "-DPYOPENMS=ON";

    buildInputs = [
      boost186
      bzip2
      coinmp
      eigen
      glpk
      kissfft
      libsvm
      openmp
      qtbase
      qtsvg
      xercesc
      xz
      yaml-cpp
      zlib
      zstd
    ]
    ++ lib.optional enablePython pythonAndPackages;

    passthru = {
      # A docker container that only includes OpenMS:
      dockerimg = import ./dockerimg.nix {
        inherit dockerTools;
        openms = package;
      };

      # Just the Python package:
      pyopenms = python3Packages.buildPythonPackage {
        pname = "pyopenms";
        version = version;
        format = "wheel";
        src = "${package}/share/whl/${wheelName}";
        dependencies = runtimePyDeps python3Packages;
        pythonImportsCheck = [ "pyopenms" ];
      };
    };

    patches = [
      ./disable-download-test.patch
      ../../patches/pyopenms-codesign-qt.patch
    ];

    postPatch = ''
      # Get rid of unnecessary uses of `which`:
      find . -type f -name '*.rb' -exec \
        sed -i -E 's/`which /`echo /g' '{}' ';'

      # Let Nix fix the RPATHs:
      (
        echo '#!${ruby}/bin/ruby'
        echo 'puts("Skip RPATH fixup")'
      ) >cmake/MacOSX/fix_dependencies.rb
    '';

    postBuild = ''
      ${lib.optionalString enablePython "make pyopenms"}

      # Needed to export TOPP XML from the built executable files:
      export QT_PLUGIN_PATH=${qtbase}/lib/qt-6/plugins
      export QT_QPA_PLATFORM=offscreen
      make doc
    '';

    postInstall = lib.optionalString enablePython ''
      mkdir -p "$out/share/whl"
      find pyOpenMS/dist -type f -name '*.whl' \
        -exec cp -a '{}' "$out/share/whl/${wheelName}" ';'
    '';

    meta = {
      description = "Open-source software for LC-MS data management and analyses";
      longDescription = ''
        OpenMS is an open-source software C++ library for LC-MS data
        management and analyses. It offers an infrastructure for rapid
        development of mass spectrometry related software. OpenMS is
        free software available under the three clause BSD license and
        runs under Windows, macOS, and Linux.
      '';
      homepage = "https://openms.de/";
      license = lib.licenses.bsd3;
      maintainers = with lib.maintainers; [ pjones ];
      platforms = lib.platforms.all;
    };
  };
in
package
